# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-west-2"
    bucket         = "delius-versions-remote-state"
    dynamodb_table = "delius-versions-lock-table"
  }
}
