# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "eu-west-2"
  version = "~> 2.61"

  # Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = ["895523100917"]
}
